export enum CategoryErrors {
    CATEGORY_ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',
    MISSING_NAME = 'MISSING_NAME',
    MISSING_CATEGORY_TYPE = 'MISSING_CATEGORY_TYPE',
    MISSING_ID = 'MISSING_ID',
    NOT_FOUND = 'NOT_FOUND',
}
