export enum TransactionErrors {
    MISSING_DATE = 'MISSING_DATE',
    MISSING_DESCRIPTION = 'MISSING_DESCRIPTION',
    MISSING_CATEGORY = 'MISSING_CATEGORY',
    MISSING_AMOUNT = 'MISSING_AMOUNT',
    MISSING_ID = 'MISSING_ID',
    NOT_FOUND = 'NOT_FOUND',
}
